# Generated by Django 5.2.7 on 2025-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('payMethod', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
