# Generated by Django 5.2.8 on 2025-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_paymethod_user_pay_method_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
