# Generated by Django 5.2.8 on 2025-11-15 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_category_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'No puede haber stock negativo')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
