# Generated by Django 5.2.8 on 2025-11-15 12:58

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    Category.objects.get_or_create(name="General")

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_service_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
