# Generated by Django 5.2.8 on 2025-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20251115_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
