# Generated by Django 5.2.8 on 2025-11-17 12:19

import app.models.order
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_productquantity_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(default=app.models.order.Order.generate_identifier, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
