# Generated by Django 5.2.8 on 2025-11-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_identifier_alter_order_user_cartitem'),
        ('app', '0013_alter_service_price'),
    ]

    operations = [
    ]
