# Generated by Django 5.2.8 on 2025-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
