# Generated by Django 5.2.8 on 2025-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
