# Generated by Django 5.2.8 on 2025-11-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_service_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='top',
            new_name='isPromoted',
        ),
    ]
