# Generated by Django 5.2.8 on 2025-11-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_top_product_ispromoted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='top',
            new_name='isPromoted',
        ),
    ]
