# Generated by Django 5.2.8 on 2025-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_cartitem_session_key_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payMethod',
            field=models.CharField(choices=[('contrarembolso', 'Contrarembolso'), ('pasarela', 'Pasarela de Pago')], default='pasarela', max_length=20),
        ),
    ]
