# Generated by Django 5.2.8 on 2025-11-22 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_cartitem_session_key_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='servicequantity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='servicequantity',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('contrarembolso', 'Contrarembolso'), ('pasarela', 'Pasarela de Pago')], default='pasarela', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Correo', 'Correo'), ('Tienda', 'Tienda'), ('Punto de entrega', 'Punto Entrega')], default='Correo', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.DeleteModel(
            name='ServiceQuantity',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='only_one_of_product_or_service_order'),
        ),
    ]
