# Generated by Django 5.2.8 on 2025-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_order_paymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_method',
            field=models.CharField(choices=[('contrarembolso', 'Contrarembolso'), ('pasarela', 'Pasarela de Pago')], default='pasarela', max_length=20),
        ),
    ]
