# Generated by Django 5.2.8 on 2025-11-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_user_pay_method'),
        ('app', '0025_alter_user_pay_method'),
    ]

    operations = [
    ]
