# Generated by Django 5.2.8 on 2025-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_merge_20251123_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_method',
            field=models.CharField(choices=[('contrarembolso', 'Contrarembolso'), ('pasarela', 'Pasarela de Pago')], default=None, max_length=50, null=True),
        ),
    ]
