# Generated by Django 5.2.8 on 2025-11-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_order_paymethod_alter_user_pay_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
