# Generated by Django 5.2.8 on 2025-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_order_paymethod_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Enviado'), ('delivered', 'Entregado')], default='pending', max_length=20),
        ),
    ]
