# Generated by Django 5.2.8 on 2025-12-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_order_paymethod_order_shipping_costs_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE app_order DROP COLUMN IF EXISTS payMethod",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]